### ISSUE TITLE
Getting error with any project if i install it in meteor.

### ISSUE THREAD

**Issue by arun99178** [ErikDakoda/vulcan-material-ui#4]
Your app is crashing. Here's the latest log:
/Users/arunkumargupta/.meteor/packages/meteor-tool/.1.6.1.1vr3nk.j9siy++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module 'graphql-server-express'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.require (/arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/boot.js:288:32)
    at makeInstallerOptions.fallback (packages/modules-runtime.js:651:18)
    at require (packages/modules-runtime.js:244:16)
    at apollo_server.js (packages/vulcan:lib/lib/server/apollo_server.js:1:49)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at main.js (packages/vulcan:lib/lib/server/main.js:1:57)
    at fileEvaluate (packages/modules-runtime.js:343:9)
    at require (packages/modules-runtime.js:238:16)
    at /arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/packages/vulcan_lib.js:3317:15
    at /arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/packages/vulcan_lib.js:3324:3
    at /arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/boot.js:411:36
    at Array.forEach (<anonymous>)
    at /arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/boot.js:220:19
    at /arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/boot.js:471:5
    at Function.run (/arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/profile.js:510:12)
    at /arun-works-file/node-work/Taherlal-Shaik/DHID-Framework/dhid-demo/.meteor/local/build/programs/server/boot.js:470:11
Exited with code: 1
Your application is crashing. Waiting for file change.

**Comment by ErikDakoda** [comment]
That means the package 'graphql-server-express' has not been added to your project. First you should do an npm install just in case:
```
meteor npm install
```
Then add the missing npm package:
```
meteor npm install --save graphql-server-express
```
If you get additional "Cannot find module" errors, you have to do the same thing for each one.
