### ISSUE TITLE
TypeError: Cannot read property 'sheetsRegistry' of undefined

### ISSUE THREAD

**Issue by enzolutions** [ErikDakoda/vulcan-material-ui#56]
I tried vulcan-material-ui with the devel branch of Vulcan, and I got this error in server side

```
// error at callback [injectJss] in hook [router.server.postrender]
TypeError: Cannot read property 'sheetsRegistry' of undefined
　  at injectJss (packages/erikdakoda:vulcan-material-ui/server/wrapWithMuiTheme.jsx:34:22)
　  at runCallback (packages/vulcan:lib/lib/modules/callbacks.js:108:33)
　  at packages/vulcan:lib/lib/modules/callbacks.js:156:16
    at Array.reduce (<anonymous>)
　  at runCallbacks (packages/vulcan:lib/lib/modules/callbacks.js:136:22)
　  at Promise.asyncApply (packages/vulcan:lib/lib/server/apollo-ssr/renderPage.js:75:5)
　  at /Users/enzo/.meteor/packages/promise/.0.11.2.1eqp2nx.ymsr++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by Julien-Sytadelle** [comment]
You must limit Vulcan version to 1.12.13 

Le 13 mars 2019 à 20:08, à 20:08, enzo - Eduardo Garcia <notifications@github.com> a écrit:

**Comment by enzolutions** [comment]
Hi, @Julien-Sytadelle how I can do that? BTW I am using a two repo install, using devel branch.

Do you think that could be a problem?

**Comment by Julien-Sytadelle** [comment]
You pull master branch @1.12.13

Le 13 mars 2019 à 20:47, à 20:47, enzo - Eduardo Garcia <notifications@github.com> a écrit:

**Comment by enzolutions** [comment]
Uhhh, there is no brach or tag with that name

```bash
git tag | grep 1.
0.14.3
1.1.0
v0.10.0
v0.11.0
v0.11.1
v0.12.0
v0.12.0-pre
v0.12.1
v0.13.0
v0.13.0rc
v0.14.0
v0.14.0-rc
v0.14.1
v0.14.2
v0.15
v0.15-rc
v0.15.1
v0.15.1-rc
v0.21.1
v0.22.1rc
v0.9.10
v0.9.11
v1.0.0
v1.11.1
v1.2.0
v1.5.0
v1.6.0
v1.7.0
v1.8
```

Thanks for your help.

**Comment by Julien-Sytadelle** [comment]
Hi, 

The problem comes from a new component missing in forms. Inner form or something like that.
If you have a solution, a lot of people would thank you. It may not be difficult to solve but I did not have any free time to dig. 

Best

Le 13 mars 2019 à 20:50, à 20:50, Julien Cornaz <jc@sytadelle.fr> a écrit:

**Comment by Julien-Sytadelle** [comment]
Sorry, not on my computer so I cannot tell you the commit Id but 1.12.13 is visible in commit history of master branch. Please note that i may have make a mistake and right version may be 1.8.13. The important number is the last one (13).

Le 13 mars 2019 à 20:54, à 20:54, enzo - Eduardo Garcia <notifications@github.com> a écrit:

**Comment by ErikDakoda** [comment]
The current version of material-ui is only compatible with Vulcan 1.12.8. An update is coming soon.

**Comment by enzolutions** [comment]
Ahh ok 

I was trying with

```
commit 553a0627d47e2cf19b6722e195c4461b4ae68634
Author: SachaG <358832+SachaG@users.noreply.github.com>
Date:   Wed Jan 2 14:41:41 2019 +0900

    v1.12.13

**Comment by enzolutions** [comment]
@ErikDakoda thanks for your support I tried with 1.12.8 and 1.12.13, but in both I got the following error in client side.

```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `FormattedMessage`.
    at invariant (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:110367:15)
    at createFiberFromTypeAndProps (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:120504:11)
    at createFiberFromElement (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:120525:15)
    at reconcileSingleElement (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:122797:23)
    at reconcileChildFibers (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:122854:35)
    at reconcileChildren (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:124668:28)
    at finishClassComponent (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:125024:5)
    at updateClassComponent (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:124962:24)
    at beginWork (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:125910:16)
    at performUnitOfWork (http://localhost:3250/packages/modules.js?hash=a0e2ed67e1dac99218e46f3f01bbeee7cf6b3b54:129578:12)
```

I checked the code in 1.12.8 but I couldbn't determine the issue.

```
import React, { Component } from 'react';
import { intlShape } from './shape';

const FormattedMessage = ({ id, values, defaultMessage = '', html = false, className = '' }, { intl }) => {
  const message = intl.formatMessage({ id, defaultMessage }, values);
  const cssClass = `i18n-message ${className}`;

  return html ? 
    <span className={cssClass} dangerouslySetInnerHTML={{__html: message}}/> :
    <span className={cssClass}>{message}</span>
}

FormattedMessage.contextTypes = {
  intl: intlShape
}

export default FormattedMessage;
```

Any recommendation in try to fix this issue, would be really appreciated.

**Comment by ErikDakoda** [comment]
You may want to try locking your Material-UI version:

`meteor npm install --save @material-ui/core@3.1.0`

**Comment by eric-burel** [comment]
It's related to Apollo2 SSR changes. I am merging and updating the package into the core. See PR #51

**Comment by kedeng** [comment]
vulcan 1.13.0, I tried this:

```
function injectJss (obj) {
  const { request:req } = obj;
  const sheets = req.sheetsRegistry.toString();
  obj.appendToHead(`<style id="jss-server-side">${sheets}</style>`);
}
```

**Comment by akmdi** [comment]
@kedeng Thanks. This solved the problem.
